"""Side-by-side excerpts: a page region next to each arm's markdown for the same passage.

    PYTHONPATH=. uv run python -m study.export

For each entry in ``EXCERPTS`` writes ``excerpts/<id>/page.png`` (the page region) plus
``excerpts/<id>/<arm>.md`` (that arm's markdown around the anchor), indexed in
``excerpts/README.md``. Only documents with ``excerpt_ok: true`` in ``sources.yaml`` may be
excerpted; any other is refused.
"""

import re
from dataclasses import dataclass, field

import pypdfium2 as pdfium
import yaml
from rapidfuzz import fuzz

from study.paths import OUT, ROOT, SOURCES

DEST = ROOT
DPI = 110


@dataclass
class Excerpt:
    id: str
    doc: str
    page: int  # 1-based
    anchor: str  # text that should appear in a correct conversion, located fuzzily in each arm
    arms: list[str]
    what: str  # one line: what the excerpt shows
    crop: tuple[float, float, float, float] = (0.0, 0.0, 1.0, 1.0)  # page fractions x0, y0, x1, y1 from top-left
    window: int = 500  # characters of markdown shown around the anchor
    notes: dict[str, str] = field(default_factory=dict)  # per-arm remark


# Curated after the full run; each one illustrates a finding in the report.
EXCERPTS: list[Excerpt] = []


def _excerpt_ok() -> dict[str, dict]:
    return {d["id"]: d for d in yaml.safe_load(SOURCES.read_text())["documents"] if d.get("excerpt_ok") is True}


def _render(pdf_path, page: int, crop: tuple[float, float, float, float], out) -> None:
    pg = pdfium.PdfDocument(pdf_path)[page - 1]
    img = pg.render(scale=DPI / 72).to_pil()
    w, h = img.size
    x0, y0, x1, y1 = crop
    img.crop((int(x0 * w), int(y0 * h), int(x1 * w), int(y1 * h))).save(out, optimize=True)


def _window(md: str, anchor: str, window: int) -> str | None:
    """Markdown around the best fuzzy match of ``anchor`` (None when nothing resembles it)."""
    flat = re.sub(r"\s+", " ", md)
    m = fuzz.partial_ratio_alignment(anchor, flat)
    if m is None or m.score < 60:
        return None
    mid = (m.dest_start + m.dest_end) // 2
    lo, hi = max(0, mid - window // 2), min(len(flat), mid + window // 2)
    return ("…" if lo else "") + flat[lo:hi] + ("…" if hi < len(flat) else "")


def export_excerpts() -> None:
    allowed = _excerpt_ok()
    root = DEST / "excerpts"
    index = ["# Excerpts\n", "Page region and each arm's markdown around the same passage. Generated by `study.export`.\n"]
    for ex in EXCERPTS:
        if ex.doc not in allowed:
            raise SystemExit(f"{ex.id}: {ex.doc} is not excerpt_ok")
        d = root / ex.id
        d.mkdir(parents=True, exist_ok=True)
        _render(ROOT / allowed[ex.doc]["path"], ex.page, ex.crop, d / "page.png")
        index.append(f"\n## {ex.id}\n\n{ex.what} — `{ex.doc}`, page {ex.page}.\n\n![page]({ex.id}/page.png)\n")
        for arm in ex.arms:
            md_path = OUT / arm / "docs" / f"{ex.doc}.md"
            text = _window(md_path.read_text(errors="replace"), ex.anchor, ex.window) if md_path.exists() else None
            body = text if text is not None else "(passage not found in this arm's output)"
            (d / f"{arm}.md").write_text(body + "\n")
            note = f" — {ex.notes[arm]}" if arm in ex.notes else ""
            index.append(f"\n**{arm}**{note}\n\n```text\n{body}\n```\n")
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text("".join(index))


def main() -> None:
    export_excerpts()
    print(f"{len(EXCERPTS)} excerpts -> {DEST / 'excerpts'}")


if __name__ == "__main__":
    main()
